import AppShell from '@repo/common/app-shell'
import '@repo/ui/globals.css'
import type { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<AppShell>{children}</AppShell>
			</body>
		</html>
	)
}
